<a href="https://colab.research.google.com/github/zzobaer09/pandas-learning/blob/main/Python_Pandas_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Complete Python Pandas Data Science Tutorial! (2025 Updated Edition)
### [Youtube](https://youtu.be/2uvysYbKdjM)

## Imports

In [2]:
import pandas as pd

## Dataframes

In [3]:
df = pd.DataFrame([[4,6,8],[6,8,10],[8,10,12]],columns=["A","B","C"],index=["X","Y","Z"])
df.head()

   A   B   C
X  4   6   8
Y  6   8  10
Z  8  10  12

In [4]:
df.index

Index(['X', 'Y', 'Z'], dtype='object')

In [5]:
df.columns.tolist()

['A', 'B', 'C']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, X to Z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [7]:
df.describe()

         A     B     C
count  3.0   3.0   3.0
mean   6.0   8.0  10.0
std    2.0   2.0   2.0
min    4.0   6.0   8.0
25%    5.0   7.0   9.0
50%    6.0   8.0  10.0
75%    7.0   9.0  11.0
max    8.0  10.0  12.0

In [8]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [9]:
df["A"].unique()

array([4, 6, 8])

In [10]:
df.shape

(3, 3)

In [11]:
df.size

9

## Loading in Dataframe from file

### Coffee

In [17]:
coffee_df = pd.read_csv("https://raw.githubusercontent.com/zzobaer09/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")
coffee_df

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [18]:
coffee_df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [19]:
coffee_df.tail()

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [20]:
coffee_df.tail(10)

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [29]:
coffee_df.sample(7)

          Day Coffee Type  Units Sold
11   Saturday       Latte          35
8      Friday    Espresso          45
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
1      Monday       Latte          15

In [53]:
coffee_df.sample(7,random_state=2)

          Day Coffee Type  Units Sold
11   Saturday       Latte          35
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
0      Monday    Espresso          25
9      Friday       Latte          35
3     Tuesday       Latte          20
1      Monday       Latte          15

### Olympics Result

#### Parquet

In [14]:
olympics_result_parquet_df = pd.read_parquet("https://github.com/zzobaer09/complete-pandas-tutorial/raw/refs/heads/master/data/results.parquet")
olympics_result_parquet_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

#### Excel

In [15]:
olympics_result_excel_df = pd.read_excel("https://github.com/zzobaer09/complete-pandas-tutorial/raw/refs/heads/master/data/olympics-data.xlsx")
olympics_result_excel_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25